import { keepCustomizedSheetValues } from '../support/sheet-review';
import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { PDFDocument } from 'pdf-lib';
import { normalizeEncounterCheckpoint } from '../../../src/shared/encounter-checkpoint';
import { createNimbCharacterSheet } from '../../fixtures/character-sheet-nimb';
import { applyCharacterSheetEditorFields, readCharacterSheetEditorFields } from '../../../src/multiplayer/character-sheet-pdf';
import { joinHostedSession, startHostedTestSession, createPublicBattle } from '../support/hosted-session';

test('três abas, criação, exportação e aprovação da troca durante combate', async ({ page }, info) => {
  const session = await startHostedTestSession();
  try {
    await joinHostedSession(page, session.inviteUrl, 'Acesso três fichas');
    await page.getByRole('button', { name: 'Ficha', exact: true }).click();
    const dialog = page.getByRole('dialog', { name: 'Ficha do personagem', exact: true });
    const tabs = dialog.getByRole('tab');
    await expect(tabs).toHaveCount(3);
    await expect(dialog.getByText('Consultar poderes e magias', { exact: true })).toHaveCount(0);
    await expect(dialog.getByRole('link', { name: 'Baixar ficha vazia', exact: true })).toBeVisible();
    const original = await createNimbCharacterSheet({ Nome: 'Primeira', Historico: '' });
    const fixed = await applyCharacterSheetEditorFields(original, await readCharacterSheetEditorFields(original), true);
    await page.locator('#web-player-sheet-input').setInputFiles({ name: 'primeira.pdf', mimeType: 'application/pdf', buffer: Buffer.from(fixed.bytes) });
    await expect(page.locator('#web-player-character-slots [role=tab][aria-selected=true]')).toContainText('Primeira');
    await expect(page.locator('#web-player-sheet-input')).toBeHidden();
    await expect(tabs.nth(0)).toContainText('Primeira');
    const downloadPromise = page.waitForEvent('download');
    await dialog.getByRole('button', { name: 'Exportar PDF editável' }).click();
    const download = await downloadPromise;
    const pdf = await PDFDocument.load(await readFile((await download.path())!));
    expect(pdf.getForm().getTextField('Nome').getText()).toBe('Primeira');
    expect(pdf.getForm().getTextField('Nome').isReadOnly()).toBe(false);
    await tabs.nth(1).click();
    await expect(page.locator('#web-player-sheet-upload')).toBeVisible();
    await dialog.getByRole('button', { name: 'Criar ficha vazia', exact: true }).click();
    const editor = page.getByRole('dialog', { name: 'Ajustar ficha', exact: true });
    await expect(editor).toBeVisible();
    const field = (name: string) => editor.locator(`[data-field-name="${name}"] input`);
    await field('NOME DO PERSONAGEM').fill('Segunda');
    await field('RAÇA').fill('Humano'); await field('ORIGEM').fill('Guarda'); await field('CLASSE').fill('Guerreiro');
    await field('Lv').fill('1');
    await field('PVs Totais').fill('20'); await field('PVs Atuais').fill('20');
    await field('PMs Totais').fill('3'); await field('PMs Atuais').fill('3');
    for (let i = 0; i < 3; i++) await editor.getByRole('button', { name: 'Força: +', exact: true }).click();
    for (let i = 0; i < 3; i++) await editor.getByRole('button', { name: 'Destreza: +', exact: true }).click();
    for (let i = 0; i < 2; i++) await editor.getByRole('button', { name: 'Constituição: +', exact: true }).click();
    await expect(editor.locator('.attribute-allocation-status')).toHaveText('Todos os 10 pontos foram alocados.');
    await editor.getByRole('button', { name: 'Validar e corrigir cálculos' }).click();
    await keepCustomizedSheetValues(page);
    await expect(editor.getByRole('button', { name: 'Validar e corrigir cálculos' })).toBeEnabled();
    await editor.getByRole('button', { name: 'Salvar e fechar', exact: true }).click();
    await expect(editor).toBeHidden();
    await page.getByRole('button', { name: 'Ficha', exact: true }).click();
    await expect(tabs.nth(1)).toContainText('Segunda');
    await page.screenshot({ path: info.outputPath('fichas-desktop.png') });
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(dialog).toBeInViewport();
    const width = await dialog.locator('.web-player-tools-card').evaluate((element) => ({ client: element.clientWidth, scroll: element.scrollWidth }));
    expect(width.scroll).toBeLessThanOrEqual(width.client + 1);
    await page.screenshot({ path: info.outputPath('fichas-mobile.png') });
    await page.setViewportSize({ width: 1280, height: 720 });
    session.server.publishBattleState(createPublicBattle({ battleStarted: true }));
    await tabs.nth(0).click();
    await expect.poll(() => session.server.getPendingSheetChangeRequests().length).toBe(1);
    const request = session.server.getPendingSheetChangeRequests()[0];
    expect(request.changes[0].after).toBe('Primeira');
    await expect(tabs.nth(1)).toHaveAttribute('aria-selected', 'true');
    expect(await session.server.decideCharacterSheetChanges(request.id, true)).toEqual({ ok: true });
    await expect(tabs.nth(0)).toHaveAttribute('aria-selected', 'true');
    await expect(page.locator('#web-player-character-slots [role=tab][aria-selected=true]')).toContainText('Primeira');
    const saved = session.server.captureEncounter();
    expect(saved.inactiveCharacters?.length).toBe(1);
    expect(saved.inactiveCharacters?.[0][1].state.currentHealth).toBe(22);
    saved.players[0].actions.standard = false;
    saved.inactiveCharacters![0][1].state.currentHealth = 7;
    saved.inactiveCharacters![0][1].state.currentMana = 1;
    const checkpoint = normalizeEncounterCheckpoint({ savedAt: Date.now(), battleStarted: true, hudVisible: true,
      musicPlaying: false, musicTime: 0, backgroundTime: 0, activeBackgroundPath: null, pendingBlackoutPhaseIndex: null,
      queuedPhaseIndexes: [], resumeMusicAfterBlackout: false, multiplayer: saved });
    expect(checkpoint).not.toBeNull();
    session.server.restoreEncounter(checkpoint!.multiplayer);
    await tabs.nth(1).click();
    await expect.poll(() => session.server.getPendingSheetChangeRequests().length).toBe(1);
    expect(await session.server.decideCharacterSheetChanges(session.server.getPendingSheetChangeRequests()[0].id, true)).toEqual({ ok: true });
    await expect(tabs.nth(1)).toHaveAttribute('aria-selected', 'true');
    const returned = session.server.captureEncounter().players[0];
    expect(returned.state.currentHealth).toBe(7); expect(returned.state.currentMana).toBe(1);
    expect(returned.actions.standard).toBe(false);
    await tabs.nth(0).click();
    await expect.poll(() => session.server.getPendingSheetChangeRequests().length).toBe(1);
    expect(await session.server.decideCharacterSheetChanges(session.server.getPendingSheetChangeRequests()[0].id, false)).toEqual({ ok: true });
    await expect(tabs.nth(1)).toHaveAttribute('aria-selected', 'true');
  } finally { await session.close(); }
});

test('limpar avisos preserva erros e revisão obrigatória; validar após editar recupera o aviso', async ({ page }) => {
  const session = await startHostedTestSession();
  try {
    await joinHostedSession(page, session.inviteUrl, 'Avisos revisados');
    await page.getByRole('button', { name: 'Ficha', exact: true }).click();
    await page.locator('#web-player-sheet-input').setInputFiles({ name: 'avisos.pdf', mimeType: 'application/pdf', buffer: await createNimbCharacterSheet({ nivel: '', Raca: 'Medusa', Historico: '- Olhar Atordoante: descrição personalizada com outro efeito.\n- Poder desconhecido: informação preservada.' }) });
    const editor = page.getByRole('dialog', { name: 'Ajustar ficha', exact: true });
    const review = editor.locator('#web-player-sheet-editor-review');
    if (await review.getAttribute('open') === null) await review.locator(':scope > summary').click();
    const comparison = review.locator('li').filter({ hasText: 'há uma diferença de texto' });
    await expect(comparison).toHaveCount(1);
    const actions = await comparison.locator('.sheet-issue-actions button').evaluateAll((buttons) => buttons.map((button) => button.getBoundingClientRect().y));
    expect(Math.max(...actions) - Math.min(...actions)).toBeLessThanOrEqual(1);
    await comparison.getByRole('button', { name: 'Limpar', exact: true }).click();
    await expect(comparison).toHaveCount(0);
    await expect(review.locator('li[data-severity="error"]')).not.toHaveCount(0);
    await expect(review.locator('li').filter({ hasText: 'não foi possível identificar' }).getByRole('button', { name: 'Limpar', exact: true })).toHaveCount(0);
    await editor.getByRole('button', { name: 'Validar e corrigir cálculos' }).click();
    await keepCustomizedSheetValues(page);
    await expect(editor.getByRole('button', { name: 'Validar e corrigir cálculos' })).toBeEnabled();
    await expect(comparison).toHaveCount(0);
    await editor.locator('[data-field-name="BossBar.Habilidades.Raca"] textarea').fill('- Olhar Atordoante: a descrição foi modificada novamente.');
    await editor.getByRole('button', { name: 'Validar e corrigir cálculos' }).click();
    await keepCustomizedSheetValues(page);
    await expect(comparison).toHaveCount(1);
    await review.getByRole('button', { name: 'Limpar todos', exact: true }).click();
    await expect(comparison).toHaveCount(0);
  } finally { await session.close(); }
});

test('identidade pesquisável aceita catálogo e texto livre; atributos separam base, ajustes e aquisições', async ({ page }, info) => {
  const session = await startHostedTestSession();
  try {
    await joinHostedSession(page, session.inviteUrl, 'Distribuição de atributos');
    await page.getByRole('button', { name: 'Ficha', exact: true }).click();
    await expect(page.locator('#web-player-sheet-status')).toBeEmpty();
    await expect(page.getByRole('button', { name: 'Upload ficha', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Criar ficha vazia', exact: true }).click();
    const editor = page.getByRole('dialog', { name: 'Ajustar ficha', exact: true });
    const race = editor.locator('[data-field-name="RAÇA"] input');
    await race.fill('moreau');
    await expect(editor.getByRole('option', { name: /Moreau — Coelho/ })).toBeVisible();
    await page.screenshot({ path: info.outputPath('identidade-pesquisa.png') });
    await editor.getByRole('option', { name: /Moreau — Coelho/ }).click();
    await expect(race).toHaveValue('Moreau — Coelho');
    const characterClass = editor.locator('[data-field-name="CLASSE"] input');
    await characterClass.fill('Guerreiro 3 / Bardo 2'); await characterClass.press('Escape');
    await expect(characterClass).toHaveValue('Guerreiro 3 / Bardo 2');
    await editor.locator('[data-field-name="Lv"] input').fill('5');
    const attribute = (name: string) => editor.getByRole('textbox', { name, exact: true });
    await editor.getByRole('button', { name: 'Constituição: Min.', exact: true }).click();
    await expect(attribute('Constituição: Base')).toHaveValue('-1');
    await editor.getByRole('button', { name: 'Força: Max.', exact: true }).click();
    await editor.getByRole('button', { name: 'Destreza: Max.', exact: true }).click();
    await expect(attribute('Força: Bônus')).toHaveAttribute('readonly', '');
    await expect(attribute('Força: Total')).toHaveValue('4');
    await expect(attribute('Força: Total')).toHaveAttribute('readonly', '');
    await expect(editor.locator('.attribute-allocation-status')).toHaveText('Todos os 10 pontos foram alocados.');
    await expect(editor.locator('.attribute-allocation-feedback')).not.toContainText('limite máximo inicial');
    await expect(attribute('Força: Total').locator('xpath=ancestor::*[contains(@class,"attribute-allocation-card")]')).toHaveAttribute('data-limit', 'maximum');
    await editor.getByRole('button', { name: '+ Adicionar ponto', exact: true }).click();
    const increase = page.getByRole('dialog', { name: 'Registrar aumento de atributo', exact: true });
    await increase.getByRole('button', { name: 'Adicionar ao rascunho' }).click();
    await expect(attribute('Força: Total')).toHaveValue('5');
    await editor.getByRole('button', { name: '+ Adicionar ponto', exact: true }).click();
    await increase.getByRole('button', { name: 'Adicionar ao rascunho' }).click();
    await expect(editor.locator('.attribute-allocation-feedback')).toContainText('uma vez por patamar');
    await editor.getByRole('button', { name: 'Remover', exact: true }).last().click();
    await expect(editor.locator('.attribute-allocation-feedback')).not.toContainText('uma vez por patamar');
    await page.screenshot({ path: info.outputPath('atributos-distribuicao.png') });
  } finally { await session.close(); }
});
