import { keepCustomizedSheetValues } from '../support/sheet-review';
import { test, expect } from '@playwright/test';
import { createNimbCharacterSheet } from '../../fixtures/character-sheet-nimb';
import { joinHostedSession, startHostedTestSession } from '../support/hosted-session';

test('RD da ficha: fontes, cancelamento, tamanho, rodapé e dano real no servidor', async ({ page }) => {
  const session = await startHostedTestSession();
  try {
    await page.setViewportSize({ width: 1280, height: 850 });
    await joinHostedSession(page, session.inviteUrl, 'RD Nimb');
    await page.getByRole('button', { name: 'Ficha', exact: true }).click();
    await page.locator('#web-player-sheet-input').setInputFiles({ name: 'rd.pdf', mimeType: 'application/pdf', buffer: await createNimbCharacterSheet({ nivel: '' }) });
    const editor = page.getByRole('dialog', { name: 'Ajustar ficha', exact: true });
    const field = (name: string) => editor.locator(`[data-field-name="${name}"]`);
    await expect(editor).toBeVisible();
    await field('Lv').locator('input').fill('10');
    await expect(field('CA').locator('input')).toHaveAttribute('readonly', '');
    const footer = editor.locator('.sheet-editor-footer');
    await expect(footer.getByRole('button', { name: 'Salvar e fechar' })).toBeVisible();
    await expect(footer.getByRole('button', { name: 'Validar e corrigir cálculos' })).toBeVisible();
    await expect(footer.getByRole('button', { name: 'Descartar importação', exact: true })).toBeVisible();
    const items = editor.locator('.is-item-row');
    const boxes = await items.evaluateAll((elements) => elements.slice(0, 2).map((element) => ({ x: element.getBoundingClientRect().x, y: element.getBoundingClientRect().y })));
    expect(boxes[0].y).toBe(boxes[1].y); expect(boxes[1].x).toBeGreaterThan(boxes[0].x);
    await field('SeleTamanho').locator('select').selectOption('Grande');
    await expect(field('ModFurtTam').locator('input')).toHaveValue('-2');
    await expect(field('BossBar.ManobrasTamanho').locator('input')).toHaveValue('2');
    const defense = editor.locator('.sheet-defense-row');
    const defenseControls = await defense.locator('input, select, button').evaluateAll((elements) => elements.map((element) => { const box = element.getBoundingClientRect(); return { y: box.bottom, x: box.x, right: box.right }; }));
    expect(Math.max(...defenseControls.map(({ y }) => y)) - Math.min(...defenseControls.map(({ y }) => y))).toBeLessThan(3);
    expect(defenseControls.at(-1)!.right).toBeLessThan(1280);
    await defense.scrollIntoViewIfNeeded();
    await page.screenshot({ path: test.info().outputPath('ficha-defesa.png') });
    await expect(editor.getByText('Todas as RD', { exact: false })).toHaveCount(0);
    await editor.getByRole('button', { name: 'Redução de dano', exact: true }).click();
    const dialog = page.getByRole('dialog', { name: 'Redução de dano', exact: true });
    await expect(dialog.getByRole('button', { name: 'Aplicar RD', exact: true })).toBeInViewport({ ratio: 1 });
    const help = dialog.locator('.rd-explanation');
    await expect(help).not.toHaveAttribute('open', '');
    await help.locator('.rd-help-icon').click();
    await expect(help).toHaveAttribute('open', '');
    await help.locator('summary').click();
    await expect(help).not.toHaveAttribute('open', '');
    await help.locator('summary').focus();
    await page.keyboard.press('Enter');
    await expect(help).toHaveAttribute('open', '');
    await page.keyboard.press('Enter');
    await expect(help).not.toHaveAttribute('open', '');
    await dialog.getByRole('spinbutton', { name: 'RD: Geral', exact: true }).fill('5');
    await dialog.getByRole('button', { name: 'Aplicar RD', exact: true }).click();
    await expect(dialog.getByRole('alert')).toContainText('nome');
    const universal = dialog.locator('tbody tr').filter({ has: page.getByRole('spinbutton', { name: 'RD: Geral', exact: true }) });
    await universal.getByLabel('Nome da fonte').fill('Vigor');
    await expect(dialog.locator('.rd-category-header')).toHaveCount(5);
    await expect(dialog.locator('.rd-source-row')).toHaveCount(0);
    await expect(dialog.locator('.rd-category-header button')).toHaveCount(0);
    await expect(dialog.locator('.rd-category-header').getByLabel('Fonte da proteção', { exact: true })).toHaveCount(0);
    const physical = dialog.locator('tbody tr').filter({ has: page.getByRole('spinbutton', { name: 'RD: Físico', exact: true }) });
    await physical.getByRole('spinbutton').fill('3');
    await physical.getByLabel('Nome da fonte').fill('Armadura');
    await dialog.getByLabel('Categoria da nova fonte').selectOption('physical');
    await dialog.getByRole('button', { name: '+ Adicionar fonte', exact: true }).click();
    const cut = dialog.locator('tbody tr').filter({ has: page.getByRole('spinbutton', { name: 'RD: Corte', exact: true }) });
    await cut.getByRole('spinbutton').fill('2');
    await cut.getByLabel('Fonte da proteção', { exact: true }).selectOption('item');
    await cut.getByLabel('Nome da fonte').fill('Escudo');
    await expect(dialog.locator('.rd-preview')).toContainText('Corte 10');
    await page.screenshot({ path: test.info().outputPath('rd-planilha.png') });
    await dialog.getByRole('button', { name: 'Aplicar RD', exact: true }).click();
    await editor.getByRole('button', { name: 'Redução de dano', exact: true }).click();
    await dialog.getByRole('spinbutton', { name: 'RD: Geral', exact: true }).fill('99');
    await dialog.getByRole('button', { name: 'Remover proteção', exact: true }).click();
    await expect(dialog.locator('.rd-source-row')).toHaveCount(0);
    await expect(dialog.locator('.rd-category-header')).toHaveCount(5);
    await dialog.getByRole('button', { name: 'Cancelar', exact: true }).click();
    await expect(editor.locator('.sheet-rd-summary')).toContainText('Geral 5 (Vigor)');
    await expect(editor.locator('.sheet-rd-summary')).toContainText('Corte 2 (Escudo)');
    const note = await field('BossBar.DefesaJustificativa').boundingBox();
    const summary = await editor.locator('.sheet-rd-summary').boundingBox();
    expect(summary!.y).toBeGreaterThanOrEqual(note!.y + note!.height - 2);
    await editor.getByRole('button', { name: 'Validar e corrigir cálculos', exact: true }).click();
    await keepCustomizedSheetValues(page);
    await expect(editor.locator('.has-import-error')).toHaveCount(0);
    await editor.getByRole('button', { name: 'Salvar e fechar', exact: true }).click();
    await expect(editor).toBeHidden();
    await expect.poll(() => session.server.getPlayerHuds()[0]?.summary?.damageReduction?.categories?.universal?.amount).toBe(5);
    const before = session.server.getPlayerHuds()[0];
    const result = await session.server.applyDirectPlayerDamage({ playerIds: [before.id.replace(/^player:/, '')], damage: 15, damageType: 'Corte', damageOrigin: 'mundane' });
    expect(result.ok).toBe(true);
    expect(result.appliedPlayers).toBe(1);
    expect(session.server.getPlayerHuds()[0].currentHealth).toBe(before.currentHealth! - 5);
    await page.getByRole('button', { name: 'Ficha', exact: true }).click();
    await page.locator('#web-player-sheet-open').click();
    await editor.getByRole('button', { name: 'Redução de dano', exact: true }).click();
    await expect(dialog.getByRole('spinbutton', { name: 'RD: Geral', exact: true })).toHaveValue('5');
    await expect(dialog.getByRole('spinbutton', { name: 'RD: Corte', exact: true })).toHaveValue('2');
    await page.setViewportSize({ width: 390, height: 844 });
    const bounds = await dialog.boundingBox(); expect(bounds!.width).toBeLessThan(391);
    await page.screenshot({ path: test.info().outputPath('rd-celular.png') });
  } finally { await session.close(); }
});
