import { keepCustomizedSheetValues } from '../support/sheet-review';
import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { createNimbCharacterSheet } from '../../fixtures/character-sheet-nimb';
import { joinHostedSession, startHostedTestSession } from '../support/hosted-session';

test('catálogo e Nimb: categorias, magias completas, custo somente leitura e uma linha de campos', async ({ page }) => {
  const session = await startHostedTestSession();
  try {
    await joinHostedSession(page, session.inviteUrl, 'Catálogo Nimb');
    await page.getByRole('button', { name: 'Ficha', exact: true }).click();
    await page.getByRole('button', { name: 'Criar ficha vazia', exact: true }).click();
    await page.getByRole('button', { name: 'Consultar catálogo', exact: true }).first().click();
    const catalog = page.getByRole('dialog', { name: 'Poderes e magias', exact: true });
    await catalog.locator('.rules-catalog-kind').selectOption('');
    await expect(catalog).toBeVisible();
    await catalog.getByRole('searchbox').fill('presente de wynlla');
    await expect(catalog.locator('.rules-catalog-detail')).toContainText('Poder geral');
    await expect(catalog.locator('.rules-catalog-detail')).toContainText('Atlas de Arton, p. 111');
    await catalog.getByRole('searchbox').fill('Arma de Jade');
    await expect(catalog.locator('.rules-catalog-detail')).toContainText('Deuses de Arton, p. 60');
    await catalog.getByRole('searchbox').fill('Açoite Flamejante');
    await expect(catalog.locator('.rules-catalog-detail')).toContainText('Ameaças de Arton, p. 404');
    await page.screenshot({ path: test.info().outputPath('catalogo-jogador.png') });
    await page.keyboard.press('Escape');
    await expect(catalog).toHaveCount(0);
    await page.getByRole('button', { name: 'Descartar importação', exact: true }).click();
    const fixtures = JSON.parse(await readFile(path.resolve('tests/fixtures/nimb-text-examples.json'), 'utf8'));
    const hudson = fixtures.find(({ name }: { name: string }) => name === 'Hudson');
    await page.locator('#web-player-sheet-input').setInputFiles({ name: 'hudson.pdf', mimeType: 'application/pdf', buffer: await createNimbCharacterSheet({ ...hudson.fields, nivel: '' }) });
    const editor = page.getByRole('dialog', { name: 'Ajustar ficha', exact: true });
    await expect(editor).toBeVisible();
    const field = (name: string) => editor.locator(`[data-field-name="${name}"]`);
    await field('Lv').locator('input').fill('10');
    await expect(field('BossBar.Nimb.Habilidades')).toHaveCount(0);
    await expect(field('HabRaçasOrigem')).toHaveCount(0);
    await expect(field('BossBar.Habilidades.Raca').locator('textarea')).toHaveValue(/Canção dos Mares/);
    await expect(field('BossBar.Habilidades.Origem').locator('textarea')).toHaveValue(/Vendedor de Carcaças/);
    await expect(field('BossBar.Habilidades.Classe').locator('textarea')).toHaveValue(/Empatia Selvagem/);
    await expect(field('BossBar.Habilidades.Gerais').locator('textarea')).toHaveValue(/Carapaça/);
    await expect(editor.locator('.is-spell-row')).toHaveCount(11);
    await expect(field('BossBar.Magia.1.Escola').locator('input')).toHaveValue('Convocação');
    await expect(field('BossBar.Magia.1.Area').locator('input')).toHaveValue('Alvo: você');
    await expect(field('BossBar.Magia.7.Execucao').locator('input')).toHaveValue('Movimento');
    await expect(field('BossBar.Magia.7.Duracao').locator('input')).toHaveValue('Cena');
    const seventh = editor.locator('.is-spell-row').nth(6);
    await seventh.locator('.sheet-spell-review summary').click();
    await expect(seventh.locator('.sheet-spell-review')).toContainText('Esperado: Padrão');
    await expect(seventh.locator('.sheet-spell-review')).toContainText('Esperado: 1 rodada');
    for (const row of await editor.locator('.sheet-spell-row').all()) {
      const controls = row.locator(':scope > label, :scope > .sheet-attack-test');
      await expect(controls).toHaveCount(8);
      const bounds = await controls.evaluateAll((items) => items.map((item) => { const r = item.getBoundingClientRect(); return { y: r.y, height: r.height }; }));
      expect(Math.max(...bounds.map(({ y }) => y)) - Math.min(...bounds.map(({ y }) => y))).toBeLessThanOrEqual(1);
      expect(Math.max(...bounds.map(({ height }) => height)) - Math.min(...bounds.map(({ height }) => height))).toBeLessThanOrEqual(1);
      await expect(row.getByRole('group', { name: 'Círculo', exact: true }).getByRole('textbox')).toHaveAttribute('readonly', '');
    }
    await seventh.scrollIntoViewIfNeeded();
    await page.screenshot({ path: test.info().outputPath('magias-uma-linha.png') });
    await editor.getByRole('button', { name: '+ Adicionar magia', exact: true }).click();
    await field('BossBar.Magia.12.Nome').locator('input').fill('Armadura Elemental');
    await field('BossBar.Magia.12.Nome').locator('input').press('Tab');
    await expect(field('BossBar.Magia.12.Circulo').locator('select')).toHaveValue('1');
    await expect(field('BossBar.Magia.12.Custo').locator('input')).toHaveValue('1');
    await expect(field('BossBar.Magia.12.Escola').locator('input')).toHaveValue('Evocação');
    await expect(field('BossBar.Magia.12.Efeito').locator('textarea')).toHaveValue(/Uma aura faiscante/);
    await field('BossBar.Magia.12.Circulo').locator('select').selectOption('5');
    await expect(field('BossBar.Magia.12.Custo').locator('input')).toHaveValue('15');
    await field('BossBar.Magia.12.Circulo').locator('select').selectOption('1');
    await editor.getByRole('button', { name: 'Validar e corrigir cálculos', exact: true }).click();
    await keepCustomizedSheetValues(page);
    await expect(field('BossBar.Magia.7.Duracao').locator('input')).toHaveValue('Cena');
    await page.setViewportSize({ width: 390, height: 844 });
    await field('BossBar.Magia.12.Nome').scrollIntoViewIfNeeded();
    const width = await editor.locator('#web-player-sheet-editor-fields').evaluate((element) => ({ client: element.clientWidth, scroll: element.scrollWidth }));
    expect(width.scroll).toBeLessThanOrEqual(width.client + 1);
    await page.screenshot({ path: test.info().outputPath('magias-mobile.png') });
    await editor.getByRole('button', { name: 'Salvar e fechar', exact: true }).click();
    await expect(editor).toBeHidden();
    await expect.poll(() => session.server.getPlayerHuds()[0]?.summary?.spells?.length).toBe(12);
    expect(session.server.getPlayerHuds()[0].summary?.abilities).toHaveLength(17);
  } finally { await session.close(); }
});
