import { _electron as electron, test, expect, type Page } from '@playwright/test';
import { mkdir, readFile } from 'node:fs/promises';
import path from 'node:path';

test('RD do chefão: editor compartilhado, absorção completa, parcelas exatas e biblioteca', async ({ browserName }, testInfo) => {
  void browserName;
  const profile = testInfo.outputPath('rd-profile'); await mkdir(profile, { recursive: true });
  const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE;
  const app = await electron.launch({ cwd: process.cwd(), args: ['.', '--no-sandbox', '--disable-gpu', '--in-process-gpu'], env: { ...env, BOSSBAR_E2E: '1', BOSSBAR_E2E_PROFILE: profile } });
  const named = async (title: string): Promise<Page> => {
    await expect.poll(async () => Promise.all(app.windows().map((page) => page.title()))).toContain(title);
    for (const page of app.windows()) if (await page.title() === title) return page;
    throw new Error(title);
  };
  try {
    await (await app.firstWindow()).getByRole('button', { name: 'Novo encontro' }).click();
    const master = await named('Controle do Mestre - BossBar T20');
    const control = await named('Painel Privado do Encontro - BossBar T20');
    const actionDraft = control.getByPlaceholder('Descreva a próxima ação para preparar os jogadores.');
    await actionDraft.fill('Rascunho em andamento durante os turnos');
    await control.evaluate(async () => { const boss = (await window.bossAPI.getState()).bosses[0]; window.bossAPI.dispatch({ type: 'damage', bossId: boss.id, amount: 1 }); });
    await expect(actionDraft).toHaveValue('Rascunho em andamento durante os turnos');
    await control.getByRole('button', { name: /Alterar Perícias/ }).click();
    const attributes = control.getByRole('dialog', { name: /Alterar perícias/ });
    await attributes.getByRole('button', { name: 'Configurar redução de dano' }).click();
    const rd = control.getByRole('dialog', { name: 'Redução de dano', exact: true });
    await expect(rd.getByRole('button', { name: 'Aplicar RD', exact: true })).toBeInViewport({ ratio: 1 });
    const universal = rd.locator('tbody tr').filter({ has: control.getByRole('spinbutton', { name: 'RD: Geral', exact: true }) });
    await universal.getByRole('spinbutton').fill('5'); await universal.getByLabel('Nome da fonte').fill('Vigor');
    await expect(rd.locator('.rd-category-header')).toHaveCount(5);
    await expect(rd.locator('.rd-source-row')).toHaveCount(0);
    await rd.getByLabel('Categoria da nova fonte').selectOption('elemental');
    await rd.getByRole('button', { name: '+ Adicionar fonte', exact: true }).click();
    await rd.getByLabel('Tipo de redução').selectOption('Fogo');
    const fire = rd.locator('tbody tr').filter({ has: control.getByRole('spinbutton', { name: 'RD: Fogo', exact: true }) });
    await fire.getByRole('spinbutton').fill('3'); await fire.getByLabel('Nome da fonte').fill('Casca');
    await rd.locator('.rd-total-chip').filter({ hasText: /^Fogo / }).hover();
    await expect(control.locator('.calculation-tooltip:visible')).toContainText('Casca: 3');
    await expect(control.locator('.calculation-tooltip:visible')).toContainText('Vigor: 5');
    await control.mouse.move(2, 2);
    await rd.getByRole('button', { name: 'Aplicar RD', exact: true }).click();
    await attributes.getByRole('button', { name: 'Aplicar', exact: true }).click();
    await expect(attributes).toBeHidden();
    await expect.poll(() => control.evaluate(async () => (await window.bossAPI.getState()).bosses[0].damageReductions?.entries.length)).toBe(1);
    const combat = control.locator('.control-combat-row');
    await expect(combat.getByRole('checkbox')).toHaveCount(0);
    const bounds = await combat.locator('input, select, button').evaluateAll((elements) => elements.filter((element) => element.getBoundingClientRect().width).map((element) => { const box = element.getBoundingClientRect(); return { bottom: box.bottom, right: box.right }; }));
    expect(Math.max(...bounds.map(({ bottom }) => bottom)) - Math.min(...bounds.map(({ bottom }) => bottom))).toBeLessThan(2);
    expect(Math.max(...bounds.map(({ right }) => right))).toBeLessThanOrEqual(control.viewportSize()?.width ?? 1280);
    await control.screenshot({ path: testInfo.outputPath('painel-dano.png') });
    const before = await control.evaluate(async () => (await window.bossAPI.getState()).bosses[0]);
    const absorbed = await control.evaluate(async (bossId) => window.bossAPI.applyHealthSequence({ bossId, type: 'damage', total: 7, hits: 3, damageType: 'Fogo', damageOrigin: 'mundane' }), before.id);
    expect(absorbed.ok).toBe(true); expect(absorbed.amountPerHit).toBe(0);
    await expect.poll(() => control.evaluate(async () => (await window.bossAPI.getState()).bosses[0].currentHealth)).toBe(before.currentHealth);
    await control.evaluate(async (bossId) => window.bossAPI.applyHealthSequence({ bossId, type: 'damage', total: 10, hits: 3, damageType: 'Corte', damageOrigin: 'mundane' }), before.id);
    await expect.poll(() => control.evaluate(async () => (await window.bossAPI.getState()).bosses[0].currentHealth)).toBe(before.currentHealth - 5);
    await control.evaluate(async () => { const boss = (await window.bossAPI.getState()).bosses[0]; window.bossAPI.dispatch({ ...boss, bossId: boss.id, type: 'configure', applyDamageReduction: false }); });
    await control.locator('.control-amount-field input').fill('10');
    await control.locator('.control-damage-type-field select').selectOption('Fogo');
    await control.locator('.control-damage-origin-field select').selectOption('mundane');
    await combat.getByRole('button', { name: /^Dano / }).click();
    await expect.poll(() => control.evaluate(async () => (await window.bossAPI.getState()).bosses[0].currentHealth)).toBe(before.currentHealth - 7);
    await control.getByRole('button', { name: /Alterar Perícias/ }).click();
    await attributes.getByRole('button', { name: 'Configurar redução de dano' }).click();
    await expect(rd.getByRole('spinbutton', { name: 'RD: Geral', exact: true })).toHaveValue('5');
    await rd.getByRole('checkbox', { name: 'Imunidade: Fogo', exact: true }).check();
    await expect(rd.locator('.rd-preview')).toContainText('Fogo Imune: 1');
    await control.screenshot({ path: testInfo.outputPath('rd-chefao.png') });
    await rd.getByRole('button', { name: 'Cancelar', exact: true }).click();
    await attributes.getByRole('button', { name: 'Fechar editor de perícias' }).click();
    const userData = await app.evaluate(({ app }) => app.getPath('userData'));
    await master.evaluate(() => window.bossAPI.dispatch({ type: 'start-battle' }));
    await app.evaluate(({ BrowserWindow }) => { BrowserWindow.getAllWindows().find((window) => window.getTitle() === 'Controle do Mestre - BossBar T20')?.close(); });
    const closed = app.waitForEvent('close');
    await master.getByRole('dialog', { name: 'Salvar o encontro antes de fechar?' }).getByRole('button', { name: 'Salvar e fechar', exact: true }).click();
    await closed;
    const library = JSON.parse(await readFile(path.join(userData, 'boss-library.json'), 'utf8'));
    expect(library.entries.some((entry: { bosses: Array<{ damageReductions?: { entries: unknown[] } }> }) => entry.bosses.some((boss) => boss.damageReductions?.entries.length === 1))).toBe(true);
  } finally { await app.close().catch(() => undefined); }
});
