import { _electron as electron, expect, test, type Page } from '@playwright/test';
import { mkdir } from 'node:fs/promises';

test('auditoria visual das janelas e modais do mestre, biblioteca, fases e cutscene', async ({ browserName }, info) => {
  void browserName;
  test.setTimeout(120_000);
  const profile = info.outputPath('profile');
  await mkdir(profile, { recursive: true });
  const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE;
  const app = await electron.launch({ cwd: process.cwd(), args: ['.', '--no-sandbox', '--disable-gpu', '--in-process-gpu'], env: { ...env, BOSSBAR_E2E: '1', BOSSBAR_E2E_PROFILE: profile } });
  const errors: string[] = [];
  const capture = async (page: Page, name: string) => {
    await page.mouse.move(2, 2);
    await page.screenshot({ path: info.outputPath(`${name}.png`), animations: 'disabled' });
  };
  const named = async (title: string) => {
    await expect.poll(async () => Promise.all(app.windows().map((page) => page.title()))).toContain(title);
    for (const page of app.windows()) if (await page.title() === title) { page.on('pageerror', (error) => errors.push(error.message)); return page; }
    throw new Error(title);
  };
  const inViewport = async (page: Page, selector: string) => {
    await expect(page.locator(selector)).toBeVisible();
    const layout = await page.locator(selector).evaluate((element) => {
      const rect = element.getBoundingClientRect();
      return { left: rect.left, top: rect.top, right: rect.right, bottom: rect.bottom, width: innerWidth, height: innerHeight, overflow: element.scrollWidth - element.clientWidth };
    });
    expect(layout.left).toBeGreaterThanOrEqual(0);
    expect(layout.top).toBeGreaterThanOrEqual(0);
    expect(layout.right).toBeLessThanOrEqual(layout.width + 1);
    expect(layout.bottom).toBeLessThanOrEqual(layout.height + 1);
    expect(layout.overflow).toBeLessThanOrEqual(1);
  };
  try {
    const launcher = await app.firstWindow();
    await expect(launcher.getByRole('button', { name: 'Novo encontro', exact: true })).toBeVisible();
    await capture(launcher, 'launcher');
    await launcher.getByRole('button', { name: 'Novo encontro', exact: true }).click();
    const master = await named('Controle do Mestre - BossBar T20');
    const control = await named('Painel Privado do Encontro - BossBar T20');
    const player = await named('Apresentação do Chefão - BossBar T20');
    await capture(master, 'master');
    await capture(control, 'control');
    await capture(player, 'player-waiting');
    await master.getByRole('button', { name: 'Biblioteca de ataques', exact: true }).click();
    const libraryPage = await named('Biblioteca de ataques - BossBar T20');
    const library = libraryPage.getByRole('dialog', { name: 'Biblioteca de ataques' });
    await library.getByRole('button', { name: 'Novo ataque', exact: true }).click();
    await library.getByLabel('Nome', { exact: true }).fill('Lâmina da noite — ataque de teste');
    await library.getByRole('button', { name: 'Adicionar efeito', exact: true }).click();
    await inViewport(libraryPage, '.attack-library');
    await expect(library.getByRole('button', { name: 'Salvar ataque', exact: true })).toBeInViewport();
    expect(await library.getByLabel('Nome', { exact: true }).evaluate((element) => getComputedStyle(element).fontFamily)).not.toMatch(/Georgia/);
    await capture(libraryPage, 'attack-library-window');
    await library.getByRole('button', { name: 'Salvar ataque', exact: true }).click();
    await expect(library.locator('article')).toHaveCount(1);
    await library.getByRole('button', { name: 'Fechar biblioteca de ataques' }).click();
    await master.getByRole('button', { name: 'Abrir configurações' }).click();
    await inViewport(master, '.settings-modal');
    await capture(master, 'settings');
    await master.getByRole('button', { name: 'Fechar configurações' }).click();
    await master.getByRole('button', { name: 'Abrir bloco de notas' }).click();
    await inViewport(master, '.master-notes-modal');
    await capture(master, 'notes');
    await master.getByRole('dialog').getByRole('button', { name: 'Fechar', exact: true }).click();
    await master.getByRole('button', { name: 'Efeitos sonoros', exact: true }).click();
    await capture(master, 'sound-effects');
    await master.getByRole('button', { name: 'Fechar personalização de efeitos sonoros' }).click();
    await master.getByRole('button', { name: 'Editar cena', exact: true }).click();
    const editor = await named('Editar Cena - BossBar T20');
    await capture(editor, 'scene');
    await editor.getByRole('button', { name: 'Escolher armas / ataques' }).click();
    const wideLibrary = editor.getByRole('dialog', { name: 'Biblioteca de ataques' });
    await wideLibrary.getByRole('button', { name: 'Editar', exact: true }).click();
    await inViewport(editor, '.attack-library');
    await expect(wideLibrary.getByRole('button', { name: 'Salvar ataque', exact: true })).toBeInViewport();
    await capture(editor, 'attack-library-wide');
    await wideLibrary.getByRole('button', { name: 'Cancelar edição', exact: true }).click();
    await editor.getByRole('dialog', { name: 'Biblioteca de ataques' }).getByRole('button', { name: 'Selecionar', exact: true }).click();
    await inViewport(editor, '.phase-arsenal');
    await expect(editor.locator('.phase-arsenal input[type="radio"]').first()).toHaveCSS('height', '16px');
    await capture(editor, 'scene-arsenal');
    for (let i = 1; i < 8; i += 1) await editor.getByRole('button', { name: 'Adicionar fase', exact: true }).click();
    await expect(editor.locator('.phase-select-button')).toHaveCount(8);
    await expect(editor.locator('.phase-select-button').last()).toBeInViewport();
    await editor.locator('.phase-select-button').first().click();
    await editor.getByLabel('Cutscene entre esta fase e a próxima').check();
    await editor.locator('.cutscene-tab').click();
    await inViewport(editor, '.cutscene-editor');
    await capture(editor, 'cutscene');
    await editor.getByRole('button', { name: 'Montar playlist', exact: true }).first().click();
    await inViewport(editor, '.scene-playlist-modal');
    await capture(editor, 'playlist');
    await editor.getByRole('button', { name: 'Fechar playlist' }).click();
    await control.getByRole('button', { name: 'Armas/Ataques', exact: true }).click();
    await inViewport(control, '.control-boss-arsenal-modal');
    await capture(control, 'arsenal');
    await control.getByRole('button', { name: 'Fechar arsenal' }).click();
    await control.locator('.control-open-attributes').click();
    await inViewport(control, '.control-attributes-modal');
    await capture(control, 'boss-attributes');
    await control.getByRole('button', { name: 'Fechar editor de perícias' }).click();
    await control.getByRole('button', { name: 'Soundboard', exact: true }).click();
    const soundboard = await named('Soundboard - BossBar T20');
    await inViewport(soundboard, '.soundboard-shell');
    await capture(soundboard, 'soundboard');
    await soundboard.getByRole('button', { name: 'Atribuir som ao botão 1', exact: true }).click();
    await inViewport(soundboard, '[role="dialog"]');
    await capture(soundboard, 'soundboard-assignment');
    await soundboard.getByRole('button', { name: 'Fechar', exact: true }).click();
    await app.evaluate(({ BrowserWindow }) => {
      BrowserWindow.getAllWindows().find((window) => window.getTitle() === 'Soundboard - BossBar T20')!.setSize(560, 560);
    });
    await inViewport(soundboard, '.soundboard-grid');
    await inViewport(soundboard, '.soundboard-controls');
    await capture(soundboard, 'soundboard-narrow');
    await master.getByRole('button', { name: 'Salvar encontro', exact: true }).click();
    await expect(master.locator('.library-status-message')).toHaveText('Encontro salvo na biblioteca.');
    await master.getByRole('button', { name: 'Carregar encontro', exact: true }).click();
    const encounters = await named('Biblioteca de Encontros - BossBar T20');
    await inViewport(encounters, '.library-shell');
    await capture(encounters, 'encounters');
    await app.evaluate(({ BrowserWindow }) => {
      BrowserWindow.getAllWindows().find((window) => window.getTitle() === 'Biblioteca de Encontros - BossBar T20')!.setSize(900, 620);
    });
    await inViewport(encounters, '.library-shell');
    await inViewport(encounters, '.library-panel');
    await capture(encounters, 'encounters-narrow');
    await master.getByRole('button', { name: 'Abrir depurador do encontro' }).click();
    const debuggerPage = await named('Depurador do Encontro - BossBar T20');
    await inViewport(debuggerPage, '.debugger-shell');
    await capture(debuggerPage, 'debugger');
    expect(errors).toEqual([]);
  } finally { await app.evaluate(({ app }) => app.exit(0)).catch(() => undefined); await app.close().catch(() => undefined); }
});
