import type { BossAPI } from './api';

export type RendererRole =
  | 'launcher'
  | 'master'
  | 'player'
  | 'control'
  | 'soundboard'
  | 'library'
  | 'scene-editor';

export const bossApiMethodsByRole = {
  launcher: [
    'hasEncounterLibraryEntries',
    'openBossLibrary',
    'startNewEncounter',
    'subscribeBossLibraryChanged',
  ],
  master: [
    'addEncounterSound',
    'confirmAppClose',
    'dispatch',
    'getAppVersion',
    'getEncounterEffectsState',
    'getEncounterSoundCustomization',
    'getMusicState',
    'getState',
    'isPresentationOpen',
    'openBossLibrary',
    'openPresentation',
    'openSceneEditor',
    'removeEncounterSound',
    'saveBossAutosave',
    'saveBossToLibrary',
    'setEncounterEffectsVolume',
    'setEncounterGeneralEnabled',
    'setEncounterSoundEnabled',
    'setEncounterSoundOptionEnabled',
    'setEncounterVisualEffectEnabled',
    'setUniversalMute',
    'subscribe',
    'subscribeAppCloseRequested',
    'subscribeBossLoaded',
    'subscribeEncounterEffects',
    'subscribeMusic',
    'subscribePresentationOpen',
    'getScenePlan',
    'releaseSceneBlackout',
    'activateSceneBlackout',
    'subscribeScenePlan',
  ],
  player: [
    'encounterEffectFinished',
    'getBackground',
    'getEncounterEffectsState',
    'getMusicState',
    'getScenePlan',
    'getSoundboardState',
    'getState',
    'musicFadeoutComplete',
    'musicTrackEnded',
    'presentationReady',
    'reportBackgroundError',
    'reportMusicProgress',
    'reportSoundEffectError',
    'soundEffectFinished',
    'subscribe',
    'subscribeBackground',
    'subscribeEncounterEffect',
    'subscribeEncounterEffects',
    'subscribeHealthEffect',
    'subscribeMusic',
    'subscribeMusicFadeOut',
    'subscribeMusicSeek',
    'subscribeScenePlan',
    'subscribeSceneTransition',
    'subscribeSoundboard',
    'subscribeSoundboardStop',
    'subscribeSoundEffect',
  ],
  control: [
    'applyHealthSequence',
    'dispatch',
    'getEncounterEffectsState',
    'getState',
    'setControlPanelMinimized',
    'openSoundboardWindow',
    'getSoundboardState',
    'dispatchSoundboard',
    'subscribe',
    'subscribeEncounterEffects',
    'subscribeSoundboard',
  ],
  soundboard: [
    'assignSoundboardSlot',
    'dispatchSoundboard',
    'getSoundboardState',
    'getState',
    'subscribe',
    'subscribeSoundboard',
    'subscribeSoundboardError',
  ],
  library: [
    'closeBossLibrary',
    'deleteBossLibraryEntry',
    'getBossLibraryEntries',
    'loadBossFromLibrary',
    'replaceBossLibraryFile',
    'subscribeBossLibraryChanged',
  ],
  'scene-editor': [
    'chooseScenePhaseMedia',
    'clearScenePhaseMedia',
    'confirmSceneEditorClose',
    'dispatchScenePhasePlaylist',
    'addScenePhasePlaylistTracks',
    'getScenePlan',
    'getState',
    'openScenePhasePlaylist',
    'saveScenePlan',
    'resetSceneDraft',
    'subscribe',
    'subscribeBackgroundError',
    'subscribeSceneEditorCloseRequested',
    'subscribeScenePhasePlaylist',
    'subscribeScenePlan',
  ],
} as const satisfies Record<RendererRole, readonly (keyof BossAPI)[]>;
